# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0007_lkupmanagementrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DRAFT', 'DRAFT'), ('LIVE', 'LIVE'), ('DEFUNCT', 'DEFUNCT')], max_length=10)),
                ('firstScore', models.IntegerField(default=0)),
                ('secondScore', models.IntegerField(default=0)),
                ('firstTeamBets', models.IntegerField(default=0)),
                ('secondTeamBets', models.IntegerField(default=0)),
                ('drawBets', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('expireDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betbase.BetCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='images')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.LKUPCountry')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='betEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betbase.BetEvent'),
        ),
        migrations.AddField(
            model_name='bet',
            name='firstTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_firstTeam', to='betbase.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='secondTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_secondTeam', to='betbase.Team'),
        ),
    ]
