# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date_defunct',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
