DATE_TIME_FORMAT = '%d-%b-%Y %H:%M'
DATE_FORMAT = '%d-%b-%Y'


DEFAULT_ITEM_PER_PAGE = 9
VIEW = 4

CODE_SUCCESS = 'success'
ERR_GENERAL = 'ERR_GENERAL'
ERR_CREATE_OBJ = 'ERR_CREATE_OBJ'
ERR_OBJ_EXIST = 'ERR_OBJ_EXIST'
ERR_OBJ_NOT_EXIST = 'ERR_OBJ_NOT_EXIST'
ERR_NOT_ALLOWED = 'ERR_NOT_ALLOWED'
ERR_INVALID_PARAMETER = 'ERR_INVALID_PARAMETER'
ERR_NO_REQUEST_USER = 'ERR_NO_REQUEST_USER'
