# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_auto_20161220_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='lkupeventtype',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=10),
        ),
    ]
