# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=800)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(null=True)),
                ('date_rejected', models.DateTimeField(null=True)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='user.AFSUser')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='user.AFSUser')),
            ],
            options={
                'db_table': 'user_connect',
            },
        ),
        migrations.AddField(
            model_name='afsuser',
            name='connect',
            field=models.ManyToManyField(through='user.UserConnect', to='user.AFSUser'),
        ),
        migrations.AddField(
            model_name='afsuser',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.LKUPCountry'),
        ),
        migrations.AddField(
            model_name='afsuser',
            name='industry',
            field=models.ManyToManyField(to='lookup.LKUPIndustry'),
        ),
        migrations.AddField(
            model_name='afsuser',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.LKUPLanguage'),
        ),
        migrations.AddField(
            model_name='afsuser',
            name='region',
            field=models.ManyToManyField(to='lookup.LKUPRegion'),
        ),
        migrations.AddField(
            model_name='afsuser',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.LKUPAccountType'),
        ),
        migrations.AddField(
            model_name='afsuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
