# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnect',
            name='acceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconnect',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
