# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161209_0544'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='afsuser',
            table='af_user',
        ),
    ]
