# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20161215_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnect',
            name='acceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='user.AFSUser'),
        ),
        migrations.AlterField(
            model_name='userconnect',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='user.AFSUser'),
        ),
    ]
