# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20161215_0550'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='afsuser',
            table='afs_user',
        ),
    ]
