# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20161216_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afsuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='afsuser',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='afsuser',
            name='type',
        ),
        migrations.AlterField(
            model_name='afsuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
