# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20161216_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afsuser',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.LKUPLanguage'),
        ),
        migrations.AlterField(
            model_name='afsuser',
            name='message',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='afsuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='afsuser',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, to='lookup.LKUPRegion'),
        ),
        migrations.AlterField(
            model_name='afsuser',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='afsuser',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
