# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20161222_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afsuser',
            name='role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
