# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20161222_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='afsuser',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
