# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_afsuser_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnect',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userconnect',
            name='date_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
