# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20161222_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='afsuser',
            name='views_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
