# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_afsuser_views_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconnect',
            unique_together=set([('requester', 'acceptor')]),
        ),
    ]
