# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20170107_1404'),
        ('user', '0014_auto_20170112_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnect',
            name='acceptor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_company', to='company.Company'),
        ),
        migrations.AddField(
            model_name='userconnect',
            name='requester_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_company', to='company.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='userconnect',
            unique_together=set([('requester', 'acceptor', 'requester_company', 'acceptor_company')]),
        ),
    ]
