# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_accountactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountactivation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_activation_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
