# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20170118_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='afsuser',
            name='mobile_cty_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='afsuser',
            name='tel_cty_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
