# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20161220_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
