# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LKUPAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lkup_account_type',
            },
        ),
        migrations.CreateModel(
            name='LKUPCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('iso', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'lkup_country',
            },
        ),
        migrations.CreateModel(
            name='LKUPIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'lkup_industry',
            },
        ),
        migrations.CreateModel(
            name='LKUPLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'lkup_language',
            },
        ),
        migrations.CreateModel(
            name='LKUPRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lkup_region',
            },
        ),
    ]
