# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_auto_20161209_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lkupcountry',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
