# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_auto_20161209_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='LKUPEventType',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lkup_event_type',
            },
        ),
        migrations.AlterField(
            model_name='lkupregion',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
