"""
Django settings for Goalsmapper project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.conf import settings
import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_PATH = os.path.abspath(os.path.dirname(__name__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lj6&#mhdpo4@l_hw!dd9%b)q^wzx!gqrc+mhpo7*0@%d^1*2gy'

# DEBUG
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#debug



ALLOWED_HOSTS = []


# Application definition

PREREQ_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites'
]
THIRD_PARTY_APPS = [
    'allauth',
    'allauth.account',
    'allauth_djrill',
    'djrill',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_auth.registration',
    'boto',
    'countries_plus',
    # 'oauth2_provider',
    # 'social.apps.django_app.default',
    # 'rest_framework_social_oauth2',
    # 'django_extensions'

]
PROJECT_APPS = [
    'apps.common',
    'apps.betbase',
    'apps.upload',
    'apps.lookup',
    'apps.authentication'

]
INSTALLED_APPS = PREREQ_APPS+THIRD_PARTY_APPS+PROJECT_APPS
MIDDLEWARE = [

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',

]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_PATH+'/../frontend/'],
        'APP_DIRS': True,
        'OPTIONS': {

            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'social.apps.django_app.context_processors.backends',
                # 'social.apps.django_app.context_processors.login_redirect',
                'apps.common.context_processors.global_settings'
            ],
        },
    },
]
STATICFILES_FINDER = ["django.contrib.staticfiles.finders.AppDirectoriesFinder"]

# EMAIL CONFIGURATION
# ------------------------------------------------------------------------------
EMAIL_BACKEND = 'djrill.mail.backends.djrill.DjrillBackend'

AUTHENTICATION_BACKENDS = [

    # Facebook OAuth2
    # 'social.backends.facebook.FacebookAppOAuth2',
    # 'social.backends.facebook.FacebookOAuth2',

    # Google OAuth2
    # 'social_auth.backends.google.GoogleOAuth2Backend'

    # Needed to login by username in Django admin, regardless of `allauth`
    # 'rest_framework_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

]
WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

SITE_ID = 1
REST_USE_JWT = True
OLD_PASSWORD_FIELD_ENABLED = True
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'apps.authentication.serializers.RegisterSerializer'
}
REST_AUTH_SERIALIZERS ={
    'JWT_SERIALIZER': 'apps.authentication.serializers.AFSJWTSerializer',
    'PASSWORD_RESET_SERIALIZER': 'apps.authentication.serializers.PasswordResetSerializer',
    'USER_DETAILS_SERIALIZER': 'apps.authentication.serializers.UserSerializer',
    'LOGIN_SERIALIZER': 'apps.authentication.serializers.AFSLoginSerializer',
}
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# USE_I18N = True
#
# USE_L10N = True

USE_TZ = False


# static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = PROJECT_PATH+'/public/'
STATIC_URL = '/public/'
STATICFILES_DIRS = (

    ( os.path.join(PROJECT_PATH, '..', 'frontend/public'),)
)


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_recommendation',
        'TIMEOUT': 60,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

DATE_INPUT_FORMATS = ('%d-%M-%Y','%Y-%m-%d')


EMAIL_BACKEND = 'djrill.mail.backends.djrill.DjrillBackend'
MANDRILL_API_KEY = "I--rT3bG1N8aazuKFE-ykw"
EMAIL_HOST = 'smtp.mandrillapp.com' # Host for sending e-mail.
# Port for sending e-mail.
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = "xiaoguo.pok@goldenequatorconsulting.com"
# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = 'Consulting'
EMAIL_HOST_PASSWORD = 'BsWMYpuBFElrYnuhn6Kt2Q'
EMAIL_USE_TLS = True

LOGIN_REDIRECT_URL ='/dashboard'



ALLOWED_HOSTS = ['127.0.0.1','localhost', 'afs.goldenequator.com','139.59.240.73','stage.asiafundspace.com','asiafundspace.com', 'www.asiafundspace.com']

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        # 'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        # 'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
     'EXCEPTION_HANDLER': 'apps.common.exception.json_exception_handler'
}

#  DJANGO ALL AUTH
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION="mandatory"
ACCOUNT_ADAPTER = 'allauth_djrill.adapter.DjrillAccountAdapter'
ACCOUNT_AUTHENTICATION_METHOD= 'email'

ALLAUTH_DJRILL_TEMPLATES = {
    'account/email/email_confirmation': 'email_confirmation',
    'account/email/email_confirmation_welcome': 'email_confirmation_welcome',
    'account/email/email_confirmation_signup': 'email_confirmation_signup',
    'account/email/password_reset_key': 'password_reset_key',
    'account/email/email_reset_password': 'email_reset_password',
    'account/email/holding': 'email_account_holding',
    'account/email/admin_new_signup': 'email_admin_new_signup'
}


JWT_AUTH = {
    "JWT_ALLOW_REFRESH": True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
    "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7)

}
AWS_KEY = "AKIAJPNVDRLRAZDBZMOA"
AWS_SECRET= "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"


CACHE_MIDDLEWARE_ALIAS = "default"
CACHE_MIDDLEWARE_SECONDS = 60
CACHE_MIDDLEWARE_KEY_PREFIX = "afs"

NOTIFICATIONS_USE_JSONFIELD = True
