# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup', '0007_lkupmanagementrole'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_activation_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile_cty_code', models.CharField(max_length=6, null=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_cty_code', models.CharField(max_length=6, null=True)),
                ('message', models.CharField(blank=True, max_length=800, null=True)),
                ('views_count', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'b_user',
            },
        ),
        migrations.CreateModel(
            name='UserConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_rejected', models.DateTimeField(blank=True, null=True)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='user.BUser')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='user.BUser')),
            ],
            options={
                'db_table': 'user_connect',
            },
        ),
        migrations.AddField(
            model_name='buser',
            name='connects',
            field=models.ManyToManyField(through='user.UserConnect', to='user.BUser'),
        ),
        migrations.AddField(
            model_name='buser',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.LKUPLanguage'),
        ),
        migrations.AlterUniqueTogether(
            name='userconnect',
            unique_together=set([('requester', 'acceptor')]),
        ),
    ]
